# openai whisper
# FROM nvcr.io/nvidia/pytorch:24.08-py3
# RUN apt update && apt install -y ffmpeg
# WORKDIR /workspace
# ADD requirements.txt /workspace/requirements.txt
# RUN pip install -U -r /workspace/requirements.txt

# faster whisper
FROM nvidia/cuda:12.2.2-cudnn8-runtime-ubuntu22.04
WORKDIR /workspace
RUN apt-get update -y && apt-get install -y python3-pip
RUN apt-get install -y ffmpeg
ADD requirements.txt /workspace/requirements.txt
RUN pip install -U -r /workspace/requirements.txt
