[client]
showSidebarNavigation = false

[server]
enableStaticServing = false
enableXsrfProtection = false
[theme]
primaryColor="#1D65A6"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F2F2F2"
textColor="#141309"
font="sans serif"